apiVersion: v1
kind: Service
metadata:
  name: result-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30005
  selector:
    name: result-pod
    app: common-name-voting
