apiVersion: v1
kind: Pod
metadata:
  name: result-pod
  labels:
    name: result-pod
    app: common-name-voting
spec:
  containers:
    - name: result-container
      image: kodekloud/examplevotingapp_result:v1
      ports:
        - containerPort: 80
