apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    name: worker-pod
    app: common-name-voting
spec:
  containers:
    - name: worker-container
      image: kodekloud/examplevotingapp_worker:v1
